{
 "title": "Explore a GBIF dataset",
 "time": { "from": "1779-12-31T23:40:28.000Z", "to": "2020-12-31T23:00:00.000Z" },
 "templating": {
  "list": [
   { "name": "minLat", "query": "1" },
   { "name": "maxLat", "query": "2" },
   { "name": "minLon", "query": "3" },
   { "name": "maxLon", "query": "4" },
   { "name": "search", "label": "Search" },
   {
    "name": "preparations",
    "label": "Preparations method",
    "query": "SELECT DISTINCT preparations FROM explore.gbif ORDER BY 1"
   }
  ]
 },
 "panels": [
  {
   "title": "Map",
   "type": "alexandra-trackmap-panel",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH a AS (\nSELECT\neventdate AS time,\ndecimallatitude,\ndecimallongitude,\ngeom,\nCOUNT(*) OVER() AS cnt\nFROM explore.gbif\nWHERE $__timeFilter(eventdate)\nAND (preparations IN ($preparations) OR NULLIF(TRIM(CONCAT($preparations)), '') IS null)\nAND decimallatitude >= $minLat\nAND decimallatitude <= $maxLat\nAND decimallongitude >= $minLon\nAND decimallongitude <= $maxLon\nAND (tsv @@ websearch_to_tsquery('simple', '$search') OR NULLIF('$search', '') IS null)\n), b AS (\nSELECT\ntime,\ndecimallatitude,\ndecimallongitude,\nST_ClusterKMeans(geom, LEAST(cnt::integer, 150)) OVER() AS clusters\nFROM a\n)\nSELECT\nclusters,\nCOUNT(clusters) AS tooltip,\nAVG(decimallatitude) AS latitude,\nAVG(decimallongitude) AS longitude\nFROM b\nGROUP BY 1\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  count(*), $__time(eventdate)\n  --$__timeGroup(\"date\",'60m')\nFROM explore.gbif\nWHERE $__timeFilter(eventdate)\nAND decimallatitude >= $minLat\nAND decimallatitude <= $maxLat\nAND decimallongitude >= $minLon\nAND decimallongitude <= $maxLon\nAND (tsv @@ websearch_to_tsquery('simple', '$search') OR NULLIF('$search', '') IS null)\nAND (preparations IN ($preparations) OR NULLIF(TRIM(CONCAT($preparations)), '') IS null)\nGROUP BY 2\nORDER BY 2 ASC"
    }
   ]
  },
  {
   "title": "Recorded by",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*), recordedby\nFROM\n  explore.gbif\nWHERE $__timeFilter(eventdate)\nAND (tsv @@ websearch_to_tsquery('simple', '$search') OR NULLIF('$search', '') IS null)\nAND (preparations IN ($preparations) OR NULLIF(TRIM(CONCAT($preparations)), '') IS null)\nAND recordedby IS NOT NULL\nAND decimallatitude >= $minLat\nAND decimallatitude <= $maxLat\nAND decimallongitude >= $minLon\nAND decimallongitude <= $maxLon\nGROUP BY 2\nORDER BY 1 DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Preparation method",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*), preparations\nFROM\n  explore.gbif\nWHERE $__timeFilter(eventdate)\nAND (tsv @@ websearch_to_tsquery('simple', '$search') OR NULLIF('$search', '') IS null)\nAND (preparations IN ($preparations) OR NULLIF(TRIM(CONCAT($preparations)), '') IS null)\nAND recordedby IS NOT NULL\nAND decimallatitude >= $minLat\nAND decimallatitude <= $maxLat\nAND decimallongitude >= $minLon\nAND decimallongitude <= $maxLon\nGROUP BY 2\nORDER BY 1 DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM explore.gbif\nWHERE $__timeFilter(eventdate)\nAND (preparations IN ($preparations) OR NULLIF(TRIM(CONCAT($preparations)), '') IS null)\nAND decimallatitude >= $minLat\nAND decimallatitude <= $maxLat\nAND decimallongitude >= $minLon\nAND decimallongitude <= $maxLon\nAND (tsv @@ websearch_to_tsquery('simple', '$search') OR NULLIF('$search', '') IS null)\nORDER BY eventdate DESC\nLIMIT 100"
    }
   ]
  }
 ]
}